packages:
  - packages/*
  - internal/*
  - playground
  - docs
catalog:
  "@commitlint/cli": ^20.4.1
  "@commitlint/config-conventional": ^20.4.1
  "@ctrl/tinycolor": ^4.2.0
  "@floating-ui/dom": ^1.7.5
  "@tsconfig/node22": ^22.0.5
  "@types/gulp": ^4.0.18
  "@types/jsdom": ^27.0.0
  "@types/lodash": ^4.17.23
  "@types/lodash-es": ^4.17.12
  "@vitejs/plugin-vue": ^6.0.4
  "@vitejs/plugin-vue-jsx": ^5.1.4
  "@vitest/eslint-plugin": 1.1.7
  "@vue/eslint-config-prettier": ^10.2.0
  "@vue/eslint-config-typescript": ^14.6.0
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.8.1
  "@vueuse/core": ^14.2.1
  async-validator: ^4.2.5
  commitizen: ^4.3.1
  cz-git: ^1.12.0
  dayjs: ^1.11.19
  escape-html: ^1.0.3
  gulp: ^5.0.1
  husky: ^9.1.7
  jsdom: ^28.0.0
  lint-staged: ^16.2.7
  lodash: ^4.17.23
  lodash-es: ^4.17.23
  lodash-unified: ^1.0.3
  memoize-one: ^6.0.0
  normalize-wheel-es: ^1.2.0
  npm-run-all2: ^8.0.4
  oxfmt: ^0.31.0
  oxlint: ^1.46.0
  sass: ^1.97.3
  tinyglobby: ^0.2.15
  tsdown: ^0.20.3
  typescript: ~5.9.3
  unocss: ^66.6.0
  unplugin-vue-components: ^31.0.0
  vite: ^8.0.0-beta.5
  vite-plugin-vue-devtools: ^8.0.6
  vitepress: ^1.6.4
  vitest: ^4.0.18
  vue: ^3.5.28
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
