packages:
  - packages/*
  - internal/*
  - playground
  - docs
catalog:
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@ctrl/tinycolor": ^4.1.0
  "@floating-ui/dom": ^1.6.13
  "@pnpm/workspace.find-packages": ^1000.0.10
  "@tsconfig/node22": ^22.0.0
  "@types/jsdom": ^21.1.7
  "@types/lodash": ^4.17.15
  "@types/lodash-es": ^4.17.12
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vitest/eslint-plugin": 1.1.7
  "@vue/eslint-config-prettier": ^10.2.0
  "@vue/eslint-config-typescript": ^14.4.0
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.7.0
  "@vueuse/core": ^12.7.0
  async-validator: ^4.2.5
  commitizen: ^4.3.1
  cz-git: ^1.11.0
  dayjs: ^1.11.13
  escape-html: ^1.0.3
  eslint: ^9.21.0
  eslint-plugin-oxlint: ^0.15.11
  eslint-plugin-vue: ^9.32.0
  husky: ^9.1.7
  jsdom: ^26.0.0
  lint-staged: ^15.4.3
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  lodash-unified: ^1.0.3
  memoize-one: ^6.0.0
  normalize-wheel-es: ^1.2.0
  npm-run-all2: ^7.0.2
  oxlint: ^0.15.12
  prettier: ^3.5.2
  typescript: ~5.7.3
  unbuild: ^3.3.1
  unocss: ^66.0.0
  vite: ^6.1.1
  vite-plugin-vue-devtools: ^7.7.2
  vitepress: ^1.6.3
  vitest: ^3.0.6
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.4
